apiVersion: platform.hsdp.io/v1alpha1
kind: Xloginfratest
metadata:
  name: loginfratest
  namespace: crossplane-system
spec:
  settings:
    instanceClass: db.t3.micro
    engine: postgres
    engineVersion: "13.7"
    dbName: postgres
    storageGB: 10
    dbSubnetGroupName: aft-740050906158-primary-db-subnet-group
    #give unique external-name for RDS so that the secret tied to it are unique and so does the rds on aws is unique
    external-name: loginfra-postgress

  resourceConfig:
    deletionPolicy: Delete
    region: us-east-1
    writeConnectionSecretNamespace: crossplane-system
    vpcSecurityGroupIds: sg-0658a688dd62752dc
    aws_provider_config_name: aws-provider
    helm_provider_config_name: helm-provider

  opensearchsettings:
    storageGB: 12
    engineVersion: OpenSearch_2.5
    instanceClass: m5.large.search
    #this needs to be unique as the access policies needs to have a fixed decided name to apply
    external-name: loginfra-opensearch
  keycloaksettings:
    keycloakVersion: 15.1.6
    #provide unique external name
    external-name: loginfra-keycloak

