apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xloginfratests.platform.hsdp.io
spec:
  group: platform.hsdp.io
  names:
    kind: Xloginfratest
    plural: xloginfratests
  claimNames:
    kind: loginfratest
    plural: loginfratests
#  connectionSecretKeys:
#    - endpoint
#    - address
#    - dbName
#    - username
#    - password
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                type: object
                description: ResourceConfig defines general settings for the resource
                properties:
                  deletionPolicy:
                    description: Defaults to Delete
                    enum:
                    - Delete
                    - Orphan
                    type: string
                  region:
                    type: string
                  writeConnectionSecretNamespace:
                    type: string
                  vpcSecurityGroupIds:
                    type: string
                  external-name:
                    description: External name for the provisioned resources
                    type: string
                    pattern: "^[a-zA-Z0-9_.-]{3,255}$"
                  aws_provider_config_name:
                    type: string
                  helm_provider_config_name:
                    type: string

                required:
                  - region
                  - writeConnectionSecretNamespace
                  - vpcSecurityGroupIds
                  - aws_provider_config_name
                  - helm_provider_config_name
              settings:
                type: object
                properties:
                  instanceClass:
                    type: string
                    description: The instance type of the RDS instance.
                  engine:
                    type: string
                    description: This RDS Instance engine, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                    enum:
                    - postgres
                    - mariadb
                    - mysql
                  dbName:
                    type: string
                    description: The name of the database to create when the DB instance is created
                  engineVersion:
                    type: string
                    description: This RDS Instance engine version, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                  storageGB:
                    type: integer
                  maxStorageGB:
                    description: "When configured, the upper limit to which Amazon RDS can automatically scale the storage of the DB instance"
                    type: integer
                  dbSubnetGroupName:
                    type: string
                  external-name:
                    type: string
#                  passwordSecretRef:
#                    type: object
#                    description: "A reference to the Secret object containing database password"
#                    properties:
#                      namespace:
#                        type: string
#                      name:
#                        type: string
#                      key:
#                        type: string
#                    required:
#                    - namespace
#                    - name
#                    - key
                required:
                  - engine
                  - engineVersion
                  - storageGB
                  - dbSubnetGroupName
                  - external-name
              opensearchsettings:
                type: object
                properties:
                  engineVersion:
                    type: string
                    description: Opensearch version
                  storageGB:
                    type: integer
                  instanceClass:
                    type: string
                  external-name:
                    type: string
                required:
                  - engineVersion
                  - storageGB
                  - instanceClass
                  - external-name
              keycloaksettings:
                type: object
                properties:
                  keycloakVersion:
                    type: string
                    description: Keycloak version
                  external-name:
                    type: string
                required:
                  - keycloakVersion
                  - external-name

        required:
          - resourceConfig
          - settings
          - opensearchsettings
          - keycloaksettings
