apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hsp-loginfra
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  project: hsp-loginfra-definition
  source:
    repoURL: https://github.com/akhileshjoshi2/hsp-loginfra.git
    path: hsp-loginfra-definition
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hsp-loginfra-claim
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  project: hsp-loginfra-claim
  source:
    repoURL: https://github.com/akhileshjoshi2/hsp-loginfra.git
    path: hsp-loginfra-claim
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  dependencies:
    - name: hsp-loginfra-definition
      namespace: